# Arduino board settings
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0

# Compiler and flags
CC = avr-gcc
CXX = avr-g++
MCU = atmega328p
F_CPU = 16000000L
FORMAT = ihex
CFLAGS = -Wall -Os -mmcu=$(MCU) -DF_CPU=$(F_CPU)

# Directories
SRC_DIR = src
BUILD_DIR = build
INCLUDE_DIR = include

# Source files
SRC_FILES := $(wildcard $(SRC_DIR)/*.cpp)
OBJ_FILES := $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.o,$(SRC_FILES))

# Arduino core source files
ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVRDUDE_CONF = /etc/avrdude.conf
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/libraries
BOARDS_TXT = /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/variants
BOOTLOADER_PARENT = /usr/share/arduino/hardware/archlinux-arduino/avr/bootloaders
BOARD_TAG    = standard

#Libraries
LIBRARIES = -larduino

# Include paths
INCLUDE_DIRS = -I$(ARDUINO_CORE_PATH) -I$(INCLUDE_DIR) -I$(ARDUINO_PLATFORM_LIB_PATH) -I$(ARDUINO_VAR_PATH)/$(BOARD_TAG) 

# Build target
TARGET = firmware

# Compilation and linking
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CFLAGS) $(INCLUDE_DIRS) -c $< -o $@

$(BUILD_DIR)/%.o: $(ARDUINO_CORE_PATH)/%.cpp
	$(CXX) $(CFLAGS) $(INCLUDE_DIRS) -c $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJ_FILES) $(ARDUINO_CORE_OBJ_FILES)
	$(CC) $(CFLAGS) $^ -o $@ $(LIBRARIES)

$(BUILD_DIR)/$(TARGET).hex: $(BUILD_DIR)/$(TARGET).elf
	avr-objcopy -O $(FORMAT) -R .eeprom $< $@

# Targets
all: $(BUILD_DIR)/$(TARGET).hex

upload: $(BUILD_DIR)/$(TARGET).hex
	avrdude -v -patmega328p -carduino -P$(ARDUINO_PORT) -b115200 -D -Uflash:w:$<:i

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all upload clean
